##################################################################################
##                      모든 패키지에 대한 린터 규칙                                 ##
##                      -----------------------------                           ##
## 패키지마다 별도의 analysis-options.yaml 파일을 정의할 필요가 없습니다.               ##
## 해당 파일이 패키지에서 찾을 수 없으면 자동으로 상위 디렉토리로 이동합니다. 자세한 내용은 여기를 참조하십시오: ##
## https://dart.dev/guides/language/analysis-options#the-analysis-options-file  ##
##################################################################################

include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    no_default_cases: true
    one_member_abstracts: false
    sort_pub_dependencies: false

##
# 개발자 API가 없는 앱 (예: 명령 줄 도구 및 플러터 애플리케이션)에 사용할 린트 규칙입니다.
##

analyzer:
  errors:
    discarded_futures: ignore

  # 자동 생성된 파일을 Dart 분석에서 제외합니다.
  exclude:
    - '**/**.freezed.dart'
    - '**/**.config.dart'
    - '**/**.module.dart'
    - '**/**.mock.dart'
    - '**/**.gr.dart'
    - '**/**.gm.dart'
    - '**/**.freezed.dart'
    - '**/**.g.dart'
    - '**/**._test.dart'
    - '**/injector.module.dart'
    - 'package/pdfrx/**'
